language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit

python:
  - "3.6"

addons:
  apt:
    packages:
      - expect-dev # provides unbuffer utility

stages:
  - linting
  - packaging

jobs:
  include:
    - stage: linting
      name: "pre-commit"
      before_install:
      install: pip install pre-commit
      script:
        pre-commit run --all --show-diff-on-failure --verbose --color always
      after_success:
    - stage: packaging
      name: "Create zip package"
      before_install:
      install: pip install -r tools/requirements.txt
      script: tools/release.py
      after_success:
