language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
services:
  - xvfb

python:
  - "3.8"

addons:
  apt:
    packages:
      - expect-dev # provides unbuffer utility

stages:
  - pre-commit
  - selenium-chrome
  - selenium-firefox

jobs:
  include:
    - stage: pre-commit
      name: "eslint, web-ext, prettier, etc..."
      install: pip install pre-commit
      script:
        - pre-commit run --all --show-diff-on-failure --verbose --color always
    - stage: selenium
      name: "Chrome"
      addons:
        chrome: stable
      install:
        - pip install -r tests/requirements.txt
        - pip install -r tools/requirements.txt
      before_script:
        - export DISPLAY=:99.0
        - python3 tools/release.py
      script:
        - python3 -m unittest tests.test_chrome
    - stage: selenium
      name: "Firefox"
      addons:
        firefox: latest
      install:
        - pip install -r tests/requirements.txt
        - pip install -r tools/requirements.txt
      before_script:
        - export DISPLAY=:99.0
        - python3 tools/release.py
      script:
        - python3 -m unittest tests.test_firefox
