language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
services:
  - xvfb

python:
  - "3.6"

addons:
  apt:
    packages:
      - expect-dev # provides unbuffer utility

stages:
  - linting
  - selenium

jobs:
  include:
    - stage: linting
      name: "pre-commit (eslint, web-ext, prettier, etc...)"
      install: pip install pre-commit
      before_script: npm install web-ext -g
      script:
        - pre-commit run --all --show-diff-on-failure --verbose --color always
    - stage: selenium
      name: "Selenium Chrome"
      addons:
        apt:
          packages:
            - chromium-chromedriver
        chrome: stable
      install:
        - pip install selenium
        - pip install -r tools/requirements.txt
      before_script:
        - export DISPLAY=:99.0
      script:
        - tools/release.py
        - python -m tests tests/test_chrome.py
